from typing import Protocol

from app.domain.booking.entity import Booking, BookingWithId


class BookingRepository(Protocol):
    async def list(self) -> list[dict]: ...

    async def get(self, booking_id: int) -> Booking: ...

    async def create(self, booking: Booking) -> BookingWithId: ...

    async def update(self, booking_id: int, booking: Booking) -> Booking: ...

    async def partial_update(self, booking_id: int, data: dict) -> Booking: ...

    async def delete(self, booking_id: int) -> bool: ...
