from typing import Protocol
from app.domain.order.entity import Order, Trade


class OrderRepository(Protocol):
    async def place(self, order: Order) -> Order: ...
    async def cancel(self, order_id: str) -> Order: ...
    async def get(self, order_id: str) -> Order: ...
    async def list_trades(self) -> list[Trade]: ...
