from typing import Protocol
from app.domain.strategy.entity import Signal, Strategy


class StrategyRepository(Protocol):
    async def list(self) -> list[Strategy]: ...
    async def get(self, strategy_id: str) -> Strategy: ...
    async def save(self, strategy: Strategy) -> Strategy: ...
    async def generate_signal(self, strategy_id: str, stock_code: str) -> Signal: ...
