from typing import Protocol
from app.domain.market_data.entity import Candle, Stock, Ticker


class MarketDataRepository(Protocol):
    async def search_stocks(self, keyword: str) -> list[Stock]: ...
    async def get_candles(self, code: str, period: str, count: int) -> list[Candle]: ...
    async def get_ticker(self, code: str) -> Ticker: ...
