from typing import Protocol
from app.domain.portfolio.entity import Balance, Position


class PortfolioRepository(Protocol):
    async def get_balance(self) -> Balance: ...
    async def get_positions(self) -> list[Position]: ...
    async def get_position(self, stock_code: str) -> Position: ...
